summary_atable: &fflo
  factor1: &factor
    - algorithm
    - algorithm_rounds
    - consensus_iterations
    - training_epochs
    - dataset
    - distribution
    - ann
  factor2: *factor
  level: &level
    - minimum_loss_achieved
    - maximum_accuracy_achieved
    - maximum_recall_achieved
    - maximum_precision_achieved
    - maximum_f1_achieved
    - mean_seconds_by_round
  operation_level: &operation_level
    - max
    - min
    - mean

anova_table:
  factor1: *factor
  factor2: *factor
  level: *level

interaction_plot: *fflo

#   box:
  
#   interaction:
  
#   manova_inter:

#   manova_var:
  
#   nemenyi:
  
#   table_grouped:
  
tuckey:
  factor:
    - algorithm
    - algorithm_rounds
    - consensus_iterations
    - training_epochs
    - dataset
    - distribution
    - ann
  level:
    - minimum_loss_achieved
    - maximum_accuracy_achieved
    - maximum_recall_achieved
    - maximum_precision_achieved
    - maximum_f1_achieved
    - mean_seconds_by_round
  
# convergence:
#   combined:
  
#   xy_scatter:
  
# data_split:
#   bubble:

# inference:
#   test:
  
#   train:

#   train_test:
  
# messages:
#   dist_info:
  
#   dist_info_type:

#   dist_msg:

#   dist_msg_type:

#   heat_info:

#   heat_msg:

# network:

#   edges:
  
#   network:
  
#   nodes:
  